#!/bin/bash

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Check for Homebrew
if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew upgrade --all

taps=(
  homebrew/dupes
  homebrew/versions
  homebrew/binary
  thoughtbot/formulae
  caskroom/cask
  caskroom/fonts
  caskroom/versions
  peco/peco
  mpv-player/mpv
  bramstein/webfonttools
)

echo "tapping..."
brew tap ${taps[@]}

binaries=(
  gnu-sed --with-default-names
  zsh
  zsh-completions
  zsh-syntax-highlighting
  zsh-history-substring-search
  python
  sqlite
  sshfs
  trash
  automake
  autoconf
  curl
  pcre
  nmap
  re2c
  mhash
  libtool
  icu4c
  gettext
  jpeg
  libxml2
  mcrypt
  gmp
  libevent
  mackup
  rcm
  moreutils
  coreutils
  findutils
  bash
  bash-completion
  grc
  hub
  wget --with-iri
  vim --override-system-vi --with-lua
  homebrew/dupes/grep
  homebrew/dupes/openssh
  homebrew/dupes/screen
  ack
  git
  graphicsmagick --with-libtiff
  lynx
  pigz
  rename
  rhino
  tree
  webkit2png
  zopfli
  rbenv
  ruby-build
  composer
  speedtest_cli
  z
  go
  encfs
  cmake
  macvim
  brew-cask
  peco
  mpv-player/mpv/libass-ct --HEAD
  mpv
  homebrew/science/vips --with-webp --with-graphicsmagick
  ffmpeg --with-theora --with-tools --with-libvorbis --with-libvpx
  ffmpeg2theora
  mobile-shell
  the_silver_searcher
  packer
  sfnt2woff
  sfnt2woff-zopfli
  woff2
)

echo "installing binaries..."
for i in "${binaries[@]}"
do
  brew install $i
done

sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

links=(
  icu4c --force
)

echo "linking..."
brew link ${links[@]}

apps=(
  filebot
  # qlstephen
  qlcolorcode
  qlmarkdown
  quicklook-json
  qlprettypatch
  quicklook-csv
  betterzipql
  qlimagesize
  webpquicklook
  suspicious-package
  font-inconsolata
  font-open-sans
  font-source-code-pro
  font-source-sans-pro
  font-source-serif-pro
  font-input
  font-m-plus
  font-clear-sans
  font-roboto
)

echo "installing apps..."
brew cask install --appdir="/Applications" ${apps[@]}
brew cask alfred link

brew cleanup
brew linkapps
