cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/binary'
tap 'homebrew/boneyard'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/fuse'
tap 'homebrew/head-only'
tap 'homebrew/php'
tap 'homebrew/science'
tap 'homebrew/services'
tap 'homebrew/versions'
tap 'mpv-player/mpv'
tap 'neovim/neovim'
tap 'thoughtbot/formulae'

brew 'openssl'
brew 'bash'
brew 'bash-completion'
brew 'mysql'
brew 'python'
brew 'git'
brew 'libpng', args: ['universal']
brew 'coreutils'
brew 'curl'
brew 'libass'
brew 'ffmpeg', args: ['with-faac', 'with-libvorbis', 'with-libvpx', 'with-theora', 'with-tools']
brew 'go'
brew 'lua'
brew 'ruby'
brew 'hub'
brew 'graphicsmagick'
brew 'imagemagick'
brew 'ipfs'
brew 'memcached'
brew 'libmemcached'
brew 'mas'
brew 'mcrypt'
brew 'mongodb'
brew 'moreutils'
brew 'node'
brew 'youtube-dl'
brew 'mpv', args: ['with-libaacs', 'with-bundle']
brew 'ruby-build'
brew 'rbenv'
brew 'rename'
brew 'speedtest_cli'
brew 'syncthing', restart_service: :changed
brew 'vim', args: ['override-system-vi', 'with-lua']
brew 'watchman'
brew 'wget', args: ['with-iri']
brew 'z'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'
brew 'homebrew/boneyard/ngrok'
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/rsync'
brew 'homebrew/fuse/encfs'
brew 'homebrew/fuse/ntfs-3g'
brew 'homebrew/php/php-version'
brew 'homebrew/php/php56'
brew 'homebrew/php/php56-igbinary'
brew 'homebrew/php/php56-mcrypt'
brew 'homebrew/php/php56-memcache'
brew 'homebrew/php/php56-memcached'
brew 'homebrew/php/php56-opcache'
brew 'homebrew/science/vips'
brew 'thoughtbot/formulae/rcm'

cask 'anatine'
cask 'bettertouchtool'
cask 'calibre'
cask 'chromium'
cask 'cloudup'
cask 'cyberduck'
cask 'filebot'
cask 'firefox'
cask 'virtualbox'
cask 'quitter'
cask 'dash'
cask 'bitbar'
cask 'imageoptim'
cask 'libreoffice'
cask 'macdown'
cask 'mou'
cask 'onyx'
cask 'qlstephen'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'screens-connect'
cask 'sequel-pro'
cask 'soundcleod'
cask 'suspicious-package'
cask 'transmission'
cask 'transmit'
cask 'tunnelblick'
cask 'vlc'
cask 'webpquicklook'

cask 'font-anonymous-pro'
cask 'font-clear-sans'
cask 'font-droid-sans'
cask 'font-droid-sans-mono'
cask 'font-droid-serif'
cask 'font-fira-code'
cask 'font-fira-mono'
cask 'font-fira-sans'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-input'
cask 'font-m-plus'
cask 'font-monoid'
cask 'font-monoisome'
cask 'font-office-code-pro'
cask 'font-open-sans'
cask 'font-open-sans-condensed'
cask 'font-roboto'
cask 'font-roboto-mono'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'

mas 'Xcode', id: 497799835
mas 'The Unarchiver', id: 425424353
mas '2Do', id: 477670270
mas 'Caffeine', id: 411246225
mas 'Things', id: 407951449
mas 'Screens', id: 446107677
mas 'Tweetbot', id: 557168941
mas 'Sip', id: 507257563
mas 'Reeder', id: 880001334
