#!/bin/sh

# Ask for the administrator password upfront.
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

source ./lib/utils

# Check for Homebrew
if test ! $(which brew); then
  e_header "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew upgrade --all

taps=(
  homebrew/dupes
  homebrew/versions
  homebrew/binary
  thoughtbot/formulae
  caskroom/homebrew-fonts
  caskroom/versions
  peco/peco
  mpv-player/mpv
  bramstein/webfonttools
)

e_header "tapping..."
for i in "${taps[@]}"
do
  brew tap $i
done

binaries=(
  gnu-sed --with-default-names
  zsh
  zsh-completions
  zsh-syntax-highlighting
  zsh-history-substring-search
  python
  sqlite
  trash
  automake
  autoconf
  curl
  pcre
  nmap
  re2c
  mhash
  libtool
  icu4c
  gettext
  jpeg
  libxml2
  mcrypt
  gmp
  libevent
  mackup
  rcm
  moreutils
  coreutils
  findutils
  bash
  bash-completion
  grc
  hub
  wget --with-iri
  vim --override-system-vi --with-lua
  homebrew/dupes/grep
  homebrew/dupes/openssh
  homebrew/dupes/screen
  ack
  git
  graphicsmagick --with-libtiff
  lynx
  pigz
  rename
  rhino
  tree
  webkit2png
  zopfli
  rbenv
  ruby-build
  speedtest_cli
  z
  go
  homebrew/fuse/encfs
  cmake
  macvim
  caskroom/cask/brew-cask
  peco
  libass
  libass-ct
  mpv
  homebrew/science/vips --with-webp --with-graphicsmagick
  ffmpeg --with-faac --with-theora --with-tools --with-libvorbis --with-libvpx
  ffmpeg2theora
  mobile-shell
  the_silver_searcher
  packer
  libav
)

e_header "installing binaries..."
for i in "${binaries[@]}"
do
  brew install $i
done

sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

links=(
  icu4c --force
)

e_header "linking..."
for i in "${links[@]}"
do
  brew link $i
done

apps=(
  filebot
  # qlstephen
  qlcolorcode
  qlmarkdown
  quicklook-json
  qlprettypatch
  quicklook-csv
  betterzipql
  qlimagesize
  webpquicklook
  suspicious-package
  font-inconsolata
  font-open-sans
  font-source-code-pro
  font-source-sans-pro
  font-source-serif-pro
  font-input
  font-m-plus
  font-clear-sans
  font-roboto
  font-roboto-mono
)

e_header "installing apps..."
for i in "${apps[@]}"
do
  brew cask install --appdir="/Applications" $i
done

brew cleanup
brew linkapps
