#!/bin/sh

export DOTFILES=~/.dotfiles

if [ ! -e ~/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
git -C ~/.vim/bundle/Vundle.vim pull
vim -u ~/.vimrc.bundles +PluginInstall +qall

git -C $DOTFILES submodule update --init
git -C $DOTFILES submodule foreach "(git checkout master; git pull)"

if [ -e ~/.oh-my-zsh/custom/pure.zsh-theme ]; then
  rm ~/.oh-my-zsh/custom/pure.zsh-theme
fi
ln -s "$DOTFILES/zsh/pure/pure.zsh" "$HOME/.zfunctions/prompt_pure_setup"

if [ ! -e ~/.rbenv ]; then
  ln -s /usr/local/opt/rbenv ~/.rbenv
fi

sudo /bin/cp -RfX $(brew --prefix osxfuse)/Library/Filesystems/osxfusefs.fs /Library/Filesystems
sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs

curl -o /usr/local/bin/gifify -O https://raw.githubusercontent.com/jclem/gifify/master/gifify.sh
chmod +x /usr/local/bin/gifify

if ! grep -Fxq "$(command -v zsh)" /etc/shells
then
  command -v zsh | sudo tee -a /etc/shells
  sudo chsh -s "$(command -v zsh)" "${USER}"
fi

# Install spot
if test ! $(which spot); then
  curl -L https://raw.github.com/guille/spot/master/spot.sh -o /usr/local/bin/spot && chmod +x /usr/local/bin/spot
fi
