#!/bin/sh

export DOTFILES=~/.dotfiles

vim -u ~/.vimrc.bundles +PlugInstall +qall

if [ ! -e ~/.rbenv ]; then
  ln -s /usr/local/opt/rbenv ~/.rbenv
fi

if [ -e $(brew --prefix osxfuse)/Library/Filesystems/osxfusefs.fs ]; then
  sudo /bin/cp -RfX $(brew --prefix osxfuse)/Library/Filesystems/osxfusefs.fs /Library/Filesystems
  sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs
fi

curl -o /usr/local/bin/gifify -O https://raw.githubusercontent.com/jclem/gifify/master/gifify.sh
chmod +x /usr/local/bin/gifify

if ! grep -Fxq "$(command -v zsh)" /etc/shells
then
  command -v zsh | sudo tee -a /etc/shells
  sudo chsh -s "$(command -v zsh)" "${USER}"
fi

# Install spot
if test ! $(which spot); then
  curl -L https://raw.github.com/guille/spot/master/spot.sh -o /usr/local/bin/spot && chmod +x /usr/local/bin/spot
fi
