#!/bin/sh

export DOTFILES=$HOME/.dotfiles

if [ ! -e $HOME/.oh-my-zsh ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git $HOME/.oh-my-zsh
fi

if [ ! -e $HOME/.config/base16-shell ]; then
  git clone git://github.com/chriskempson/base16-shell.git $HOME/.config/base16-shell
fi
