#!/bin/sh

export DOTFILES=~/.dotfiles

if [ ! -e ~/.oh-my-zsh ]; then
  git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
fi

if [ ! -e ~/.config/base16-shell ]; then
  git clone git://github.com/chriskempson/base16-shell.git ~/.config/base16-shell
fi

if [ ! -e ~/.npm-packages ]; then
  mkdir ~/.npm-packages
fi
