#!/usr/bin/env zsh

function updateall() {
  update_commands=(
    "rcup -d $DOTFILES"
    "brew update"
    "brew upgrade --all"
    "brew prune"
    "brew cleanup"
    "brew linkapps"
    "$DOTFILES/bin/brew-cask-cleanup"
    "composer self-update"
    # "phpbrew self-update"
    # "phpbrew known --update"
    "$DOTFILES/bin/nvmup"
    "npm cache clean -g"
    "$DOTFILES/lib/npm-upgrade.sh"
    "gem update"
    "gem update --system"
    "mas upgrade"
    "zgen selfupdate"
    "zgen update"
  )

  printf "\n**** Running: $i *****\n\n"
  for i in "${update_commands[@]}"; do
    printf "\n**** Running: $i *****\n\n"
    eval ${i}
  done
}
